# Generated by Django 5.2.5 on 2026-08-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_websitestat_value_numeric'),
    ]

    operations = [
        migrations.CreateModel(
            name='SathvamVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(db_index=True, help_text='Year the video belongs to (e.g. 2025, 2026)')),
                ('video_id', models.CharField(help_text='YouTube video ID', max_length=20, unique=True)),
                ('title', models.CharField(help_text='Video title / speaker name', max_length=255)),
                ('published_at', models.DateField(blank=True, help_text='Date the video was published on YouTube', null=True)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order within the year (lower = first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sathvam Video',
                'verbose_name_plural': 'Sathvam Videos',
                'ordering': ['year', 'order', 'id'],
            },
        ),
    ]
