# Generated by Django 5.2.5 on 2026-08-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_sathvam_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='SathvamPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(help_text='Year this playlist belongs to', unique=True)),
                ('playlist_id', models.CharField(help_text='YouTube playlist ID (e.g. PLqbrDbtQp9Jr...)', max_length=60, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether to include this playlist during sync')),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='Last time this playlist was synced', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sathvam Playlist',
                'verbose_name_plural': 'Sathvam Playlists',
                'ordering': ['-year'],
            },
        ),
    ]
