# Generated by Django 5.2.5 on 2026-08-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_sathvam_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='sathvamplaylist',
            name='playlist_url',
            field=models.URLField(default='', help_text='Full YouTube playlist URL (e.g. https://youtube.com/playlist?list=PLxxx...)', max_length=300),
        ),
        migrations.AlterField(
            model_name='sathvamplaylist',
            name='playlist_id',
            field=models.CharField(editable=False, help_text='Auto-extracted playlist ID', max_length=60, unique=True),
        ),
    ]
