# Generated by Django 6.1 on 2026-08-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_seed_dhyana_vahini_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='DhyanaVahiniText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(db_index=True)),
                ('roll_number', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('reflection', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dhyana Vahini Text Reflection',
                'verbose_name_plural': 'Dhyana Vahini Text Reflections',
                'ordering': ['year', 'roll_number', 'id'],
                'constraints': [models.UniqueConstraint(fields=('year', 'roll_number'), name='unique_dhyana_text_year_roll_number')],
            },
        ),
    ]
