# Generated by Django 5.2.5 on 2026-08-23 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_dhyanavahinitext'),
        ('website', '0008_seed_sathvam_data'),
    ]

    operations = [
    ]
