# Generated by Django 5.2.5 on 2026-08-23 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_seed_dhyana_vahini_data'),
        ('website', '0008_seed_sathvam_data'),
    ]

    operations = [
    ]
