# Generated by Django 5.2.5 on 2026-08-24 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_merge_0008_dhyanavahinitext_0008_seed_sathvam_data'),
        ('website', '0009_merge_20260823_1434'),
    ]

    operations = [
    ]
