# Generated by Django 5.2.5 on 2026-08-24 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_merge_20260824_1309'),
        ('website', '0012_seed_dhyana_vahini_text_data'),
    ]

    operations = [
    ]
