# Generated by Django 5.2.5

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_merge_20260824_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], help_text='Month this edition covers.')),
                ('year', models.PositiveIntegerField(db_index=True, help_text='Year this edition covers.')),
                ('title', models.CharField(blank=True, help_text='Optional custom title. Defaults to "<Month> <Year>" if left blank.', max_length=255)),
                ('flipbook_url', models.URLField(help_text='HeyZine flip-book link opened when a reader clicks "Read newsletter".', max_length=500, unique=True)),
                ('cover_image_url', models.URLField(blank=True, help_text='Optional cover image URL shown on the card.', max_length=500)),
                ('cover_image', models.ImageField(blank=True, help_text='Optional cover image upload. Takes precedence over the cover image URL.', null=True, upload_to='newsletters/covers/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Newsletter',
                'verbose_name_plural': 'Newsletters',
                'ordering': ['-year', 'month', 'id'],
                'constraints': [models.UniqueConstraint(fields=('year', 'month'), name='unique_newsletter_year_month')],
            },
        ),
    ]
