# Generated by Django 5.2.5

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_merge_20260824_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Netritvam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.PositiveSmallIntegerField(help_text='Serial number within its year (e.g. 1, 2, 3 ...).')),
                ('year', models.PositiveIntegerField(db_index=True, help_text='Year this issue belongs to.')),
                ('title', models.CharField(blank=True, help_text='Optional custom title. Defaults to "Netritvam-<serial_number>" if left blank.', max_length=255)),
                ('publication_url', models.URLField(help_text='HeyZine flip-book link opened when a reader clicks "Read publication".', max_length=500, unique=True)),
                ('cover_image_url', models.URLField(blank=True, help_text='Optional cover image URL shown on the card.', max_length=500)),
                ('cover_image', models.ImageField(blank=True, help_text='Optional cover image upload. Takes precedence over the cover image URL.', null=True, upload_to='netritvam/covers/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Netritvam',
                'verbose_name_plural': 'Netritvam',
                'ordering': ['-year', 'serial_number', 'id'],
                'constraints': [models.UniqueConstraint(fields=('year', 'serial_number'), name='unique_netritvam_year_serial')],
            },
        ),
    ]
