# Generated by Django 5.2.5 on 2026-08-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_merge_20260824_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrernaEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(help_text='Year this edition belongs to', unique=True)),
                ('title', models.CharField(help_text='Display title (e.g. Prerana 2026)', max_length=255)),
                ('description', models.CharField(blank=True, default='', help_text='Optional short description (e.g. Batch XII)', max_length=500)),
                ('pdf_url', models.URLField(help_text='Google Drive shareable link for the PDF (or folder link)', max_length=500)),
                ('cover_image_url', models.URLField(blank=True, default='', help_text='Optional cover image URL. If blank, the year number is shown.', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Prerna Edition',
                'verbose_name_plural': 'Prerna Editions',
                'ordering': ['-year'],
            },
        ),
    ]
