# Generated by Django 5.2.5 on 2026-09-02 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_merge_20260824_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(db_index=True, help_text='The year this card belongs to, e.g. 2025.')),
                ('title', models.CharField(help_text='Card title, e.g. "Induction", "Valedictory", "Sai Hira".', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('drive_folder_url', models.URLField(blank=True, help_text='Google Drive folder link. Set the folder to "Anyone with the link → Viewer". Photos are pulled in automatically when you save (or click "Sync from Drive").', max_length=500)),
                ('drive_folder_id', models.CharField(blank=True, editable=False, max_length=100)),
                ('cover_image_url', models.URLField(blank=True, help_text='Optional cover image URL. If blank, the first photo is used as the cover.', max_length=600)),
                ('cover_image', models.ImageField(blank=True, help_text='Optional cover image upload. Takes precedence over the cover image URL.', null=True, upload_to='gallery/covers/')),
                ('photo_count', models.PositiveIntegerField(default=0, editable=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first within a year.')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Photo Gallery',
                'verbose_name_plural': 'Photo Gallery',
                'ordering': ['-year', 'order', 'id'],
                'indexes': [models.Index(fields=['year', 'is_active', 'order'], name='website_gal_year_c0d27f_idx')],
                'constraints': [models.UniqueConstraint(fields=('year', 'title'), name='unique_album_title_per_year')],
            },
        ),
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_file_id', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('thumbnail_link', models.URLField(help_text='Small CDN image used in the grid.', max_length=600)),
                ('full_link', models.URLField(help_text='Larger image used in the lightbox.', max_length=600)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='website.galleryalbum')),
            ],
            options={
                'verbose_name': 'Gallery photo',
                'verbose_name_plural': 'Gallery photos',
                'ordering': ['album', 'order', 'id'],
                'indexes': [models.Index(fields=['album', 'is_active', 'order'], name='website_gal_album_i_a39b60_idx')],
                'constraints': [models.UniqueConstraint(fields=('album', 'drive_file_id'), name='unique_photo_per_album')],
            },
        ),
    ]
