# Generated by Django 5.2.5 on 2026-08-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_seed_prerna_editions'),
    ]

    operations = [
        migrations.AddField(
            model_name='prernaedition',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Upload a cover image file (preferred). Overrides the URL if both are set.', null=True, upload_to='prerna/covers/'),
        ),
        migrations.AlterField(
            model_name='prernaedition',
            name='cover_image_url',
            field=models.URLField(blank=True, default='', help_text='Or paste an external image URL. Used only if no file is uploaded above.', max_length=500),
        ),
        migrations.AlterField(
            model_name='prernaedition',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Optional short description', max_length=500),
        ),
    ]
