# Generated by Django 5.2.5 on 2026-09-02 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_seed_gallery_data'),
        ('website', '0015_seed_newsletter_data'),
        ('website', '0016_prerna_cover_image'),
    ]

    operations = [
    ]
