# Generated by Django 5.2.5 on 2026-09-15 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_fix_dhyana_vahini_text_seed'),
        ('website', '0020_seed_admissions_setting'),
    ]

    operations = [
    ]
