# Generated by Django 5.2.5 on 2026-09-18 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_merge_20260915_2314'),
        ('website', '0021_update_prerna_pdf_urls'),
        ('website', '0023_seed_samithi_photos'),
    ]

    operations = [
    ]
