# Generated by Django 5.2.5 on 2026-10-06 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_seed_netritvam_cover_images'),
        ('website', '0025_seed_newsletter_cover_images'),
    ]

    operations = [
    ]
