# Generated by Django 5.2.5 on 2026-10-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_merge_20261007_0101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('year', models.PositiveIntegerField(db_index=True)),
                ('state', models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Chandigarh', 'Chandigarh'), ('Dadra and Nagar Haveli and Daman and Diu', 'Dadra and Nagar Haveli and Daman and Diu'), ('Delhi', 'Delhi'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Ladakh', 'Ladakh'), ('Lakshadweep', 'Lakshadweep'), ('Puducherry', 'Puducherry')], db_index=True, max_length=60)),
                ('gender', models.CharField(choices=[('Mahila', 'Mahila'), ('Gents', 'Gents')], max_length=10)),
                ('category', models.CharField(choices=[('spiritual', 'Spiritual Wing'), ('service', 'Service Wing'), ('education', 'Education Wing'), ('youth', 'Youth Wing'), ('medical', 'Medical / Healthcare'), ('rural', 'Rural Development'), ('environment', 'Environment'), ('other', 'Other')], db_index=True, help_text='Which wing / category this project belongs to.', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('document_url', models.URLField(help_text='Link to the project document (opened via the "View" link on the card).', max_length=600)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first within the same sort tier.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-year', 'state', 'id'],
                'indexes': [models.Index(fields=['is_active', 'year'], name='website_pro_is_acti_e63ffd_idx'), models.Index(fields=['category'], name='website_pro_categor_c99a6d_idx'), models.Index(fields=['state'], name='website_pro_state_7b1d2e_idx')],
            },
        ),
    ]
