# Generated by Django 5.2.5 on 2026-09-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_seed_testimonials_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Optional cover image upload. Takes precedence over everything else.', null=True, upload_to='testimonials/covers/'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='cover_image_url',
            field=models.URLField(blank=True, help_text='Optional cover image URL. Used if no file is uploaded above. If neither is set, a thumbnail is auto-derived from the Drive video.', max_length=500),
        ),
    ]
