# Generated by Django 5.2.5 on 2026-10-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0028_seed_projects"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                fields=("title", "year"), name="unique_project_title_per_year"
            ),
        ),
    ]
