# Generated by Django 5.2.5 on 2026-10-09 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_testimonial_cover_fields'),
        ('website', '0029_project_unique_project_title_per_year'),
    ]

    operations = [
    ]
