# Generated by Django 5.2.5 on 2026-10-09 06:20

from django.db import migrations, models


INITIAL_VIDEOS = [
    {
        'video_id': '6V7zg9Scggc',
        'title': 'Samithi Connect Video Reflection 1',
        'order': 1,
    },
    {
        'video_id': 'uTHZ16ibW0k',
        'title': 'Samithi Connect Video Reflection 2',
        'order': 2,
    },
]


def seed_samithi_videos(apps, schema_editor):
    SamithiConnectVideo = apps.get_model('website', 'SamithiConnectVideo')
    for video in INITIAL_VIDEOS:
        SamithiConnectVideo.objects.update_or_create(
            video_id=video['video_id'],
            defaults={
                'title': video['title'],
                'order': video['order'],
                'published_at': None,
                'is_active': True,
            },
        )


def unseed_samithi_videos(apps, schema_editor):
    SamithiConnectVideo = apps.get_model('website', 'SamithiConnectVideo')
    SamithiConnectVideo.objects.filter(
        video_id__in=[video['video_id'] for video in INITIAL_VIDEOS],
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_merge_20261009_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='SamithiConnectVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('published_at', models.DateField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Samithi Connect Video',
                'verbose_name_plural': 'Samithi Connect Videos',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RunPython(seed_samithi_videos, unseed_samithi_videos),
    ]
